name: ZombieMiners
version: 1.0
description: Zombies randomly pawn holding pickaxes.
authors: [JosephCW]
website: http://www.github.com/josephcw/ZombieMiners
main: com.josephcw.zombieminers.ZombieMiners